version: '3.3'
services:
  react_docker:
    container_name: react_docker
    restart: always
    image: curso-practica:v2
    hostname: react_docker
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          VERSION_ARG: 19
          PORT_ARG: 3000
    ports:
      - "8084:3000"
    networks:
      - network
    volumes:
      - ./:/app
    environment:
      REACT_APP_PORT: 3000
      REACT_APP_API_KEY: AIzaSyBVnxe4vEus9pWG07QJg3fzU_McgyDM1Lk
      REACT_APP_AUTHDOMAIN: curso-devops-91f91.firebaseapp.com
      REACT_APP_DATABASEURL: https://curso-devops-91f91-default-rtdb.firebaseio.com
      REACT_APP_PROJECTID: curso-devops-91f91
      REACT_APP_STORAGEBUCKET: curso-devops-91f91.appspot.com
      REACT_APP_MESSAGINGSENDERID: 107072111736
      REACT_APP_APPID: 1:107072111736:web:280de55c2c793db84c598d
      REACT_APP_MEASUREMENTID: G-FGN4FZQ18P
    
volumes:
  react_docker_data:
networks:
  network:
    external: true
